
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elvfccelbfwrguhrdpwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdmZjY2VsYmZ3cmd1aHJkcHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzU5NzAsImV4cCI6MjA1ODIxMTk3MH0.bb8IBPtehsZEotQ1V89RUhh61sorwNkBkWW_uLAvo_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
